ccflags-y :=	    -Wall					\
		    -DGIT_COMMIT=\"$(GIT_COMMIT)\"		\
		    -D$(CPU_ARCH)				\
		    -D$(DIST)					\
		    -DKVER_MAJOR=$(KVER_MAJOR)			\
		    -DKVER_MINOR=$(KVER_MINOR)			\
		    -I$(PWD)

crypto_test-y := main.o                   \
                 rdx_crypto.o                           

obj-m := crypto_test.o
